test('throws invalid number', async () => {})
